# Generated by Django 5.2.1 on 2025-05-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='user_mobile_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
